sonar.projectKey=matheesha-course-service
sonar.organization=your-sonarcloud-org
sonar.projectName=Course Service

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**
